### ISSUE TITLE
BTC node state changing back and forth betweenNBXplorerSynching and notstarted

### ISSUE THREAD

**Issue by Kennnyoung** [dgarage/NBXplorer#299]
Hi I am unavailable to get BTC node to a ready state. It just switch between notstarted and synching

I used docker-compose.yml to run everything on aws
 ```
bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:0.19.0.1
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-mainnet}
      BITCOIN_WALLETDIR: "/walletdata"
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        port=39388
        rpcbind=0.0.0.0
        whitelist=0.0.0.0/0

        prune=550
    expose:
      - "43782"
      - "39388"
    volumes:
      - bitcoin_datadir:/data
      - bitcoin_wallet_datadir:/walletdata
```
```
nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.1.14
    command: --noauth
    expose:
      - "32838"
    ports:
      - "32838:32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-mainnet}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "btc,ltc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      NBXPLORER_LTCRPCURL: http://litecoind:43782/
      NBXPLORER_LTCNODEENDPOINT: litecoind:39388
      NBXPLORER_RMQHOST: rabbitmq
      NBXPLORER_RMQVIRTUAL: /
      NBXPLORER_RMQUSER: **
      NBXPLORER_RMQPASS: **
      NBXPLORER_RMQTRANEX: NewTransaction
      NBXPLORER_RMQBLOCKEX: NewBlock
    volumes:
      - nbxplorer_datadir:/datadir
      - bitcoin_datadir:/root/.bitcoin
      - litecoin_datadir:/root/.litecoin
```

Below are the logs I get:
info: Configuration:  BTC: RPC connection successful
info: Configuration:  BTC: Full node version detected: 190001
info: Configuration:  BTC: Loading chain from cache...
info: Configuration:  BTC: Height: 661061
info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (bitcoind:39388)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Configuration:  BTC: Loading chain from node
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 661061
info: Explorer:       BTC: Starting scan at block 659576
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
info: Explorer:       BTC: Block download seems to hang, let's reconnect to this node
info: Events:         BTC: Node state changed: NBXplorerSynching => NotStarted
info: Configuration:  BTC: Testing RPC connection to http://bitcoind:43782/
info: Explorer:       BTC: Closed connection with node
info: Configuration:  BTC: RPC connection successful
info: Configuration:  BTC: Full node version detected: 190001
info: Configuration:  BTC: Loading chain from cache...
info: Configuration:  BTC: Height: 661061
info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (bitcoind:39388)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Configuration:  BTC: Loading chain from node
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 661061
info: Explorer:       BTC: Starting scan at block 659576
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching

Previously it will go from NBXplorerSynching => Ready, which is the expected behaviour

If anyone has any input its greatly appreciated!
