### ISSUE TITLE
RPC Issues

### ISSUE THREAD

**Issue by christianwdev** [dgarage/NBXplorer#339]
Hey,

I've been trying to debug this for a few days now, but I bought a VPS and setup a bitcoin node, https://hub.docker.com/r/nicolasdorier/docker-bitcoin, after syncing it I tried setting up my nbxplorer and no matter if I add rpcuser and password, or leave it blank, I always get the same error of "Error connecting to the RPC server Cannot assign requested address"

Here are my commands.

DOCKERBITCOIN
docker run -v ${PWD}/data:/home/bitcoin/.bitcoin -it --rm nicolasdorier/docker-bitcoin:0.21.1  

NBXPLORER
docker run -it nicolasdorier/nbxplorer:2.2.5 --btcrpccookiefile="$PWD/home/bitcoin/.bitcoin/.cookie"

Not entirely sure what I'm doing wrong, any help is appreciated.

Here's the logs for each startup

DOCKERBITCOIN
https://hastebin.com/socobuzuya.apache

NBXPLORER
https://hastebin.com/zepominuce.yaml

**Comment by NicolasDorier** [comment]
I don't know, here is an example of docker-compose we run in prod

```yml
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:2.2.5
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "bitcoin_datadir:/root/.bitcoin"
```
