### ISSUE TITLE
issue with nbx tag 2.3.40 and higher

### ISSUE THREAD

**Issue by lvnilesh** [dgarage/NBXplorer#385]
Use tag `2.3.40` or higher `image: nicolasdorier/nbxplorer:2.3.40` and try creating an invoice using with btcpayserver and see this error in nbxplorer logs

```
nbxplorer        | NBitcoin.RPC.RPCException: No wallet is loaded. Load a wallet using loadwallet or create a new one with createwallet. (Note: A default wallet is no longer automatically created)
```

This tag `2.3.39` and all the tags lower than `image: nicolasdorier/nbxplorer:2.3.39` work just fine with btcpayserver

Wonder what am I missing?

Appreciate your help. Thanks.

**Comment by NicolasDorier** [comment]
Can you show the full exception, not just one line?

**Comment by NicolasDorier** [comment]
Also, which bitcoin version?

**Comment by lvnilesh** [comment]
Thanks.

bitcoind version [23.0 released](https://bitcoincore.org/en/2022/04/25/release-23.0/) running in an intel nuc at ` 192.168.1.2`

my docker-compose.yaml on a big linux box below.
```
version: '3.9'
services:
  postgres:
    container_name: btcpay-postgres
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U btcpay"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - btcpay
    ports:
      - 5432
    volumes:
      - $PWD/postgres:/var/lib/postgresql/data
      - $PWD/initialize/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

  nbxplorer:
    restart: unless-stopped
    # image: nicolasdorier/nbxplorer:2.3.40
    image: nicolasdorier/nbxplorer:2.3.39
    container_name: nbxplorer
    restart: always
    networks:
      - btcpay
    expose:
      - 24444
    environment:
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=nbx;Password=nbx;Host=postgres;Port=5432;Database=nbx;Application Name=nbxplorer;MaxPoolSize=20;
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
      NBXPLORER_NOAUTH: 0
      NBXPLORER_NETWORK: mainnet
      NBXPLORER_BIND: 0.0.0.0:24444
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://192.168.1.2:8332
      NBXPLORER_BTCRPCUSER: user
      NBXPLORER_BTCRPCPASSWORD: pass
      NBXPLORER_BTCNODEENDPOINT: 192.168.1.2
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    volumes:
      - $PWD/nbxplorer-data:/datadir

  btcpayserver:
    container_name: btcpayserver
    restart: unless-stopped
    image: btcpayserver/btcpayserver:1.6.12
    networks:
      - btcpay
    ports:
      - 23000:23000
    expose:
      - 23000
    environment:
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:24444/
      # BTCPay settings
      BTCPAY_CHAINS: btc
      BTCPAY_VERBOSE: true
      BTCPAY_POSTGRES: User ID=btcpay;Password=btcpay;Host=postgres;Port=5432;Application Name=btcpayserver;Database=btcpay
      BTCPAY_EXPLORERPOSTGRES: User ID=nbx;Password=nbx;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=80;Database=nbx
      BTCPAY_NETWORK: mainnet
      BTCPAY_BIND: 0.0.0.0
      BTCPAY_ROOTPATH: /
      BTCPAY_DOCKERDEPLOYMENT: "true"
      BTCPAY_HOST: btcpay.domain.com
      REVERSEPROXY_DEFAULT_HOST: btcpay.domain.com
      BTCPAYGEN_LIGHTNING: lnd
    links:
      - postgres
    volumes:
      - $PWD/btcpay-data:/datadir
      - $PWD/btcpay-plugins:/root/.btcpayserver/Plugins
      - $PWD/nbxplorer-data:/root/.nbxplorer:ro
      - ${PWD}/lnd:/data/.lnd:ro
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres

  cloudflared:
    container_name: btcpay-tunnel
    image: erisamoe/cloudflared
    command: tunnel --no-autoupdate run btcpay
    restart: unless-stopped
    environment:
      REAL_IP_HEADER: Cf-Connecting-Ip
    volumes:
      - $PWD/cloudflared:/etc/cloudflared
    depends_on:
      - btcpayserver
    networks:
      - btcpay

  lnd:
    image: lightninglabs/lnd:v0.15.4-beta
    user: 1000:1000
    container_name: lnd
    volumes:
      - ${PWD}/lnd:/data/.lnd
      - ${PWD}/lnd:/root/.lnd
      - ${PWD}/secrets/lnd-password.txt:/data/.lnd/walletpassword
      - ${PWD}/secrets/lnd-password.txt:/root/.lnd/walletpassword
    restart: on-failure
    ports:
      - "9735:9735"
      - "10009:10009"
      - "8080:8080"
    environment:
      HOME: /data
    depends_on: [ nbxplorer ]
    stop_grace_period: 10m30s
    networks:
      - btcpay

  RTL:
    image: shahanafarooqui/rtl:0.13.1
    environment:
      RTL_CONFIG_PATH: /RTLConfig
      MACAROON_PATH: /LNDMacaroon
      LN_SERVER_URL: https://lnd:8080
      LN_IMPLEMENTATION: LND
    volumes:
      - $PWD/RTL/:/RTLConfig
      - $PWD/lnd/data/chain/bitcoin/mainnet/:/LNDMacaroon
      - $PWD/lnd/:/root/.lnd
      - $PWD/lndbackup/:/root/backup
    ports:
      - 3001:3000
    depends_on: [ lnd ]
    networks:
      - btcpay

networks:
  btcpay:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 192.168.48.0/24
          gateway: 192.168.48.1
```
